### ISSUE TITLE
A problem when catkin build 

### ISSUE THREAD

**Issue by CcenShuai** [engcang/FAST-LIO-SAM-QN#3]
Hi. 
Thanks for your work!
 But sadly i meet the problem as follows when catkin build:
![fba387f6-f4b7-49b5-a78e-85e5227fb712](https://github.com/engcang/FAST-LIO-SAM-QN/assets/154319919/1489cf73-cac2-4664-80dc-481b778b1829)
Is this normal? Can you give me some advice?

**Comment by engcang** [comment]
Hi @CcenShuai 
Change these lines into shared library and then please let me know if it works.

https://github.com/engcang/nano_gicp/blob/ed7567a78fc80eb9b1ee2013b9ab348374cb9e43/CMakeLists.txt#L46-L50

```cmake
#add_library(nanoflann STATIC src/nanoflann.cc) #before
add_library(nanoflann src/nanoflann.cc) #after
target_link_libraries(nanoflann ${PCL_LIBRARIES})
### NanoGICP
#add_library(nano_gicp STATIC src/nano_gicp.cc) #before
add_library(nano_gicp src/nano_gicp.cc) #after
target_link_libraries(nano_gicp ${PCL_LIBRARIES} ${EIGEN3_LIBS} ${OpenMP_LIBS} nanoflann)
```

**Comment by CcenShuai** [comment]
> Hi @CcenShuai Change these lines into shared library and then please let me know if it works.
> 
> https://github.com/engcang/nano_gicp/blob/ed7567a78fc80eb9b1ee2013b9ab348374cb9e43/CMakeLists.txt#L46-L50
> 
> ```cmake
> #add_library(nanoflann STATIC src/nanoflann.cc) #before
> add_library(nanoflann src/nanoflann.cc) #after
> target_link_libraries(nanoflann ${PCL_LIBRARIES})
> ### NanoGICP
> #add_library(nano_gicp STATIC src/nano_gicp.cc) #before
> add_library(nano_gicp src/nano_gicp.cc) #after
> target_link_libraries(nano_gicp ${PCL_LIBRARIES} ${EIGEN3_LIBS} ${OpenMP_LIBS} nanoflann)
> ```

Thanks for your reply!
It works!
But then i try the project https://github.com/engcang/FAST-LIO-Localization-QN , and meet another problem.
That is when i  change the saved_map address to where i saved **.bag** file and then run roslaunch fast_lio_localization_qn run.launch lidar:=ouster , it shows nothing.
![img_v3_026t_ed7c4728-c499-44dc-835f-d4202a33852g](https://github.com/engcang/FAST-LIO-SAM-QN/assets/154319919/3a03ab07-687c-48b4-bec3-1e95a399bba9)

**Comment by CcenShuai** [comment]
> > Hi @CcenShuai Change these lines into shared library and then please let me know if it works.
> > https://github.com/engcang/nano_gicp/blob/ed7567a78fc80eb9b1ee2013b9ab348374cb9e43/CMakeLists.txt#L46-L50
> > ```cmake
> > #add_library(nanoflann STATIC src/nanoflann.cc) #before
> > add_library(nanoflann src/nanoflann.cc) #after
> > target_link_libraries(nanoflann ${PCL_LIBRARIES})
> > ### NanoGICP
> > #add_library(nano_gicp STATIC src/nano_gicp.cc) #before
> > add_library(nano_gicp src/nano_gicp.cc) #after
> > target_link_libraries(nano_gicp ${PCL_LIBRARIES} ${EIGEN3_LIBS} ${OpenMP_LIBS} nanoflann)
> > ```
> 
> Thanks for your reply! It works! But then i try the project https://github.com/engcang/FAST-LIO-Localization-QN , and meet another problem. That is when i change the saved_map address to where i saved **.bag** file and then run roslaunch fast_lio_localization_qn run.launch lidar:=ouster , it shows nothing. ![img_v3_026t_ed7c4728-c499-44dc-835f-d4202a33852g](https://private-user-images.githubusercontent.com/154319919/294896661-3a03ab07-687c-48b4-bec3-1e95a399bba9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MjE1NzAsIm5iZiI6MTcwNDcyMTI3MCwicGF0aCI6Ii8xNTQzMTk5MTkvMjk0ODk2NjYxLTNhMDNhYjA3LTY4N2MtNDhiNC1iZWMzLTFlOTVhMzk5YmJhOS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOFQxMzQxMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYjhmZjUxMzllNzhkN2Y4YmNlOThmNDQ3NzhmZjkzNzRiOTYxNTk1YzQxMjFlM2Y2YTJiYjg5MTExYzJhZWYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cFTi1KEjg05tN41BLsUD5LMCx5Hy9u8zQ9yu3jG5-I0)

I am sorry , i  just forgot to rosbag play mybag....................

**Comment by engcang** [comment]
Great! seems there is no more issue, closing this.
